server.port=8080
spring.application.name=kitchen
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# Flyway
spring.flyway.enabled=true

spring.jpa.hibernate.ddl-auto=validate

jwt.expiration=900
jwt.secret=${JWT_SECRET}
allowed.origin=${ALLOWED_ORIGIN}


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
management.endpoints.web.exposure.include=health,info

spring.profiles.active=dev

management.server.port=8081

