spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
cookie.secure = true
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
logging.level.root=INFO
logging.level.org.springframework=WARN
logging.level.com.example.kitchen=INFO
